In [1]:
import numpy as np

In [8]:
# Buat matrix X ukuran 2x3
X = np.array([[2, 6, 8],
              [4, 5, 6]])

In [9]:
print("Matrix X:")
print(X)

Matrix X:
[[2 6 8]
 [4 5 6]]


In [10]:
# Tampilkan ukuran matrix
print("\nUkuran matrix X:", X.shape)


Ukuran matrix X: (2, 3)


In [11]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0])


Kolom pertama:
[2 4]


In [12]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :])


Baris kedua:
[4 5 6]


2. ulangi soal nomor 1 menggunakan pytorch

In [13]:
import tensorflow as tf


In [15]:
# Buat matrix X ukuran 2x3
X = tf.constant([[2, 6, 8],
                 [4, 5, 6]])


In [20]:
print("Matrix X:")
print(X)

Matrix X:
tf.Tensor(
[[2 6 8]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [19]:
#  Tampilkan ukuran matrix
print("Shape X:", X.shape)


Shape X: (2, 3)


In [21]:
# Kolom pertama
print("Kolom pertama:", X[:, 0])


Kolom pertama: tf.Tensor([2 4], shape=(2,), dtype=int32)


In [22]:
# Baris kedua
print("Baris kedua:", X[1, :])

Baris kedua: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


3. ulangi soal nomor 1 menggunakan tensorflow

In [23]:
import tensorflow as tf


In [25]:
# Buat matrix X ukuran 2x3
X = tf.constant([[2, 6, 8],
                 [4, 5, 6]])


In [26]:
print("Matrix X:")
print(X)

Matrix X:
tf.Tensor(
[[2 6 8]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [27]:
# Tampilkan ukuran matrix
print("Ukuran (shape) X:", X.shape)



Ukuran (shape) X: (2, 3)


In [28]:
# Kolom pertama
print("Kolom pertama:", X[:, 0])


Kolom pertama: tf.Tensor([2 4], shape=(2,), dtype=int32)


In [29]:
# Baris kedua
print("Baris kedua:", X[1, :])

Baris kedua: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
