In [1]:
import numpy as np

In [18]:
# buat vector x dengan ukuran 3x1
x = np.array([80, 25, 2])
x

array([80, 25,  2])

In [4]:
# hitung panjang vector x
len(x)

3

In [5]:
# tampilkan ukuran vector x
x.shape

(3,)

In [13]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [14]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

array([80])

In [15]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. lakukan transpose pada vector x dan simpan pada variabel x_t

In [25]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([80, 25,  2])

In [26]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [27]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[30, 5, 10]])
y

array([[30,  5, 10]])

In [28]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

3 . Pytorch dan Tensorflow


In [29]:
import torch
import tensorflow as tf

In [30]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_pt = torch.tensor([30, 5, 10])
x_pt

tensor([30,  5, 10])

In [31]:
# tampilkan ukuran dari vector x_t
x_tf = tf.Variable([30, 5, 10])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([30,  5, 10], dtype=int32)>